# Name
title: "Lydia Cortez"

url: "https://lylyco.github.io"
baseurl: ""

# Add your social links
social:
  - platform: LinkedIn
    url: "https://www.linkedin.com/in/lydia-cortez"
  - platform: GitHub
    url: "https://github.com/lylyco"

# Description of your website. This is used for social sharing.
description: "Lydia Cortez"

# A brief blurb about yourself
content: |
  <div class="email-row">
    <p>
      üìß
      <span id="copyEmail" style="cursor:pointer; color:#928287; font-weight:580; text-decoration:underline;">
        cortez0715@gmail.com
      </span>
      <span id="copyConfirm" style="display:none; font-size:0.9em; color:#dc0093; margin-left:20px;">
        Copied!
      </span>
    </p>
  </div>
  <div class="bio">
      üëãüèΩ I architect and lead business systems and technical operations that strengthen governance,
      reduce operational risk, and scale mission critical workflows.
    <p>
      Over the past decade, I have driven both strategy and execution across eCommerce, CRM, EHR, compliance, 
      logistics, payments, billing, and subscription based revenue models. I have strengthened commission and 
      reconciliation processes by diagnosing complex data breakdowns, resolving edge cases, and collaborating 
      with engineering to deliver durable, long term fixes.
    </p>

    <p>
      In my current nonprofit leadership role, I serve as the organization's first Data Manager, where I 
      introduced structured planning, Agile style execution, and continuous improvement practices. I 
      advance data governance frameworks and stabilize core data infrastructure to improve reporting 
      accuracy, protect data integrity, strengthen program accountability, and ensure system reliability.
    </p>
  </div>

# General settings
markdown: kramdown
sharing_image: half-sm.jpg

#### LAYOUT OPTIONS #####
# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
