# Name
title: "Hi, I'm Lydia!"

# Description of your website. This is used for social sharing.
description: "Portfolio | Lydia Cortez"

# A brief blurb about yourself
content: |
  <div class="bio">
    <p>
      Systems Strategy and Technical Operations Leader with over eight years of experience across Ecommerce, SaaS, EHR, and financial services platforms. 
      I turn complex operational challenges into structured, scalable systems that improve visibility, reduce customer friction, lower costs, and increase team productivity.
    </p>

    <p>
      I specialize in deep data analysis, uncovering structural blind spots and edge cases that impact performance and decision making. I ramp quickly in unfamiliar environments 
      and prioritize quality, thoughtful planning, and long term durability over short term fixes.
    </p>

    <p>
      Equally technical and people focused, I build trust through accountability and consistency. Curious and solution driven, I apply critical thinking and creativity to design 
      systems that work for everyone and support sustainable growth.
    </p>
  </div>

  <div class="email-row">
    ðŸ“§<span id="copyEmail" style="cursor:pointer; color:#9a3864; font-weight:600; text-decoration:underline;">
    cortez0715@gmail.com
    </span>
    <span id="copyConfirm" style="display:none; font-size:0.9em; color:#9a3864; margin-left:6px;">Copied!</span>
  </div>

# Add your social links
social:
  - platform: LinkedIn
    url: "https://www.linkedin.com/in/lydia-cortez"
  - platform: GitHub
    url: "https://github.com/lylyco"
  

# General settings
markdown: kramdown
sharing_image: half-sm.jpg

#### LAYOUT OPTIONS #####
# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
