# Name
title: '<span style="font-weight:480;">Lydia Cortez</span>'

# Add your social links
social:
  - platform: LinkedIn
    url: "https://www.linkedin.com/in/lydia-cortez"
  - platform: GitHub
    url: "https://github.com/lylyco"

# Description of your website. This is used for social sharing.
description: "Lydia Cortez"

# A brief blurb about yourself
content: |
  <div class="email-row">
  <p> </p>
    <p>
      üìß
      <span id="copyEmail" style="cursor:pointer; color:#f500a4 font-weight:600; text-decoration:underline;">
        cortez0715@gmail.com
      </span>
      <span id="copyConfirm" style="display:none; font-size:0.9em; color:#ff29b8; margin-left:6px;">
        Copied!
      </span>
    </p>
  </div>
  <div class="bio">
    <p>About Me üëãüèΩ</p>
    <p>
      I architect and lead business systems and technical operations that strengthen governance,
      reduce operational risk, and scale critical workflows.
    </p>

    <p>
      Over the past decade, I have led strategy and execution across eCommerce, CRM, EHR,
      compliance, logistics, payments, and billing, including subscription and recurring revenue models.
      I have improved commission and reconciliation systems by resolving complex data failures,
      addressing edge cases, and partnering closely with engineering to implement durable solutions.
      My work has strengthened revenue integrity, reporting accuracy, and operational reliability
      across fulfillment and financial workflows.;
    </p>

    <p>
      In my current nonprofit leadership role, I advance data governance frameworks, enhance
      program management workflows, and stabilize data infrastructure to improve reporting
      integrity, accountability, and long term system resilience.
    </p>
  </div>

# General settings
markdown: kramdown
sharing_image: half-sm.jpg

#### LAYOUT OPTIONS #####
# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
